### PR TITLE
Add timestamp to backup directory

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Why is this needed? The folder is deleted if it was there? And then it should not cause problems.

**Comment by nickvergessen** [comment]
Well if you cancel and restart for whatever reason, you will get a mixed state in there. alternatively we could delete and recreate the folder.

**Comment by MorrisJobke** [comment]
> Well if you cancel and restart for whatever reason, you will get a mixed state in there. alternatively we could delete and recreate the folder.

But this is deleted right below the line you changed. 🤔

**Comment by nickvergessen** [comment]
Hmm @schiessle had this on his own instance and with a customer

**Comment by MorrisJobke** [comment]
> Hmm @schiessle had this on his own instance and with a customer

What's in the updater log file?

**Comment by schiessle** [comment]
While looking at the code and thinking about the situation again I think the issue was the following:


1. They started the update process
2. The updater already started replacing the files
3. updater process stopped in between because of some broken read/write permissions
4. The started the updater again.
5. Now the first backup was replaced with the backup of the mixed up version
6. Now they where in the state where they had no more backup from before the first try but only the mixed up one.

This could be solved by keeping the previous backups and not replacing them. Either by adding a timestamp (like suggested by Joas) or a counter to the backups.

**Review by schiessle — APPROVED** [review]
Think this should make the update routine more robust and make sure that no backups are lost if the update process has to be restarted.

**Comment by kesselb** [comment]
```
if(file_exists($backupFolderLocation)) {
    $this->silentLog('[info] backup folder location exists');
    $this->recursiveDelete($backupFolderLocation);
}
```

Can go. It's super unlikely that a folder that includes a timestamp already exist.

**Review by MorrisJobke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
stable19 d2fe011 4e5a4a7 307f4ab c170b91
stable18 1961b61 7e8a3ef 8a569cf 08ec3d5
stable17 940e53f 2b516ba ec70d32 19da79f

**Pull request merged**
