### PR TITLE
Allow custom logfile location

### PR DESCRIPTION
**Pull request by justin-sleep**
This PR allows the specification of a custom path to the updater log in the Nextcloud server config, e.g.:
```php
'logfile_updater' => '/var/log/nextcloud/updater.log',
```

### CODE REVIEW

**Comment by solracsf** [comment]
Please resolve conflict and document it on https://github.com/nextcloud/server (config.sample.php)

**Comment by justin-sleep** [comment]
@solracsf I've rebased on master and created a PR for the docs at nextcloud/server#33928 :+1:

**Review by solracsf — APPROVED** [review]

**Comment by kesselb** [comment]
It's possible to put the data for the updater to a different location (many thanks @solracsf).

Is it still necessary to have a additional configuration option for the updater logfile? Usually there is not much written to it anyway.

**Comment by justin-sleep** [comment]
That raises a good point, @kesselb. This PR predates that addition, and my data directory being S3-mounted storage was causing some issues with the update process. Looks like I can configure `updatedirectory` to solve that problem now.

That being said, I think there is still some value in adding the option for people who like to organize their file-based logs in one location (e.g. `/var/log/nextcloud`).

**Pull request closed without merging**
