### PR TITLE
fix(integrity): expect pkg mgmt files

### PR DESCRIPTION
**Pull request by blizzz**
upgading to 27.1.0 RC3 failes because these files are included intentionally

~~building the phar files for me though~~ managed to

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Oh, sorry for missing that

**Comment by blizzz** [comment]
> Oh, sorry for missing that

Missed that, too, as i was looking for exclude lists, not allow lists. Even visited this repo :-/

**Comment by joshtrichards** [comment]
These files also now exist in the v25.0.11 release artifact. Was that intentional? It appears to be causing issues like nextcloud/server#40456.

**Pull request merged**
