### PR TITLE
Ignore custom app folders

### PR DESCRIPTION
**Pull request by juliushaertl**
This PR adds custom app folders that are within the nextcloud root to the expected files list and ignores them when deleting.

Fix for https://github.com/nextcloud/updater/issues/40

### CODE REVIEW

**Comment by juliushaertl** [comment]
ping @MorrisJobke @LukasReschke :wink:

**Comment by MorrisJobke** [comment]
@juliushaertl I added to integration tests to cover this 😉

**Comment by MorrisJobke** [comment]
Tests ran fine -> merge

**Comment by juliushaertl** [comment]
Great. Thank you very much @MorrisJobke 
Tests look fine as well. :+1:

**Comment by godfuture** [comment]
Looks nice! Will this be available on the 11.x branch as well?

**Comment by badmark** [comment]
Seeing this same error when attempting to upgrade from 13.0.4 to 13.0.6 - is there a fix?

**Comment by MorrisJobke** [comment]
> Seeing this same error when attempting to upgrade from 13.0.4 to 13.0.6 - is there a fix?

Yes  jt is shipped starting with upgrades from 13.0.6 and 14.0.0 since we updated the updater then.

**Pull request merged**
