### PR TITLE
Add further files which are going to ship with Nextcloud v30+

### PR DESCRIPTION
**Pull request by AndyScherzinger**
due to https://github.com/nextcloud/server/pull/45244

so @blizzz does this cover everything? I.e. the renamings I did are covered or should I revert them to keep things easier?
Besides that there are 2 new folders `.reuse` and `LICENSES`.I kept the old file in the list as well: `AUTHORS`

Not sure where the logic is to remove the `COPYING-README.md` from the package  as mentioned by you for `COPYING-README`

The way I read it, if a file from the expected list is missing, that isn't an issue. Just the other way around.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Nevermind... I reverted the renamings. So it is now just about the 2 additional folders

**Comment by blizzz** [comment]
Needs a `make updater.phar`

**Comment by AndyScherzinger** [comment]
> Needs a make updater.phar

Can't do that since I am not running linux

**Review by blizzz — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks a lot for the merge and the updates on the php matrix 👍

**Pull request merged**
