### PR TITLE
Use shipped.json file from new release

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix for https://github.com/nextcloud/server/issues/16939

### CODE REVIEW

**Comment by juliushaertl** [comment]
Hm strange CI failure:

```
Curl error: Failed to connect to download.nextcloud.com port 443: Connection refused (Exception)
52
```

**Comment by juliushaertl** [comment]
Ah also failing on the other branches. @rullzer Any idea why the connection might not work from the drone server?

**Comment by kesselb** [comment]
> We noticed that you request many releases once every hour which stressed our download server quite hard. We blocked access for you for now. To resolve the issue and maybe improve the download scripts you can reach out to the Nextcloud team.

cc @nextcloud/infrastructure could you whitelist drone? ;) I also see this locally when running make test one or two times.

**Comment by rullzer** [comment]
Ok so it is because we blocked the default php useragent. Since we got like million fo requests per day from those... setting the useragent seems to do the trick

**Comment by juliushaertl** [comment]
The issue occured first with text on Nextcloud 17 however since 16 is EOL just backporting to 19 for the dashboard migration from app store to shipped should be enough and https://github.com/nextcloud/server/issues/16939 is not really a huge issue.

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Why? This was intentional to delete the files of the OLD release and thus needs to check the old shipped.json for the files to delete. In this way it would delete the old files, that are in the new shipped.json.

**Comment by rullzer** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/

**Comment by kesselb** [comment]
@rullzer wrong pr :)

**Comment by juliushaertl** [comment]
Ah indeed we should then probably delete from both the old and new shipped json to be on the save side that we remove both:
- apps that got removed in the new release (before this pr)
- apps that were installed before from the app store and are now part of the release (this pr)

**Comment by MorrisJobke** [comment]
> * 
> * apps that were installed before from the app store and are now part of the release (this pr)

That was the missing information I was looking for :)

**Comment by MorrisJobke** [comment]
Mind to open a pull request so this can go in into the maintenance releases?

**Pull request merged**
