### PR TITLE
[CLI only] Add option to skip backup.

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by kesselb** [comment]
> Any reason this is a draft?

Untested yet. I will build it later and use it to update my production instance.

**Comment by kesselb** [comment]
Works on My Machine.

**Comment by MorrisJobke** [comment]
Will be shipped in 19.0.2, 18.0.8 and 17.0.9.

**Comment by acsfer** [comment]
@kesselb @MorrisJobke this command doesn't output in 19.0.2:

```
php ./updater/updater.phar --help

Usage:
  update

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  This command fetches the latest code that is announced via the updater server and safely replaces the existing code with the new one.
```

**Comment by MorrisJobke** [comment]
Ooops .... we forgot to build the phar.

**Comment by MorrisJobke** [comment]
Next releases will contain it. Or you just download it from this repo and place it in the updater folder manually.

**Comment by MorrisJobke** [comment]
> Next releases will contain it. Or you just download it from this repo and place it in the updater folder manually.

19.0.4, 18.0.10 and 17.0.10

**Comment by jackrsteiner** [comment]
I'm wondering if there's an option that's the inverse of --no-backup? Like, if you don't want updater to run, but just want the updater step 3 to run, is there an occ or updater command for this already? I think this is sort of a necessary compliment to updater --no-backup.

**Comment by joshtrichards** [comment]
@jackrsteiner No there isn't. I doubt there will be within the Updater itself. The backup functionality here is more intended for the Updater's own use. It's not backing up your data directory (files) nor your database. It's just the installation files (well, and your `config/` folder).

**Pull request merged**
