### PR TITLE
Handle symlinks in updater correctly

### PR DESCRIPTION
**Pull request by ggeorgg**
Also delete symlinked files, so that the updater does not stop when deleting a non-empty directory.

What do you think of this pull-request? @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Code wise this looks good 👍 Haven't tested yet. What are the exact steps to reproduce? Link some files inside Nextcloud? How did you manage to get there?

**Comment by MorrisJobke** [comment]
Also could you update https://github.com/nextcloud/updater/blob/master/lib/Updater.php with the exact same changes? Then the CI job also get's green.

**Comment by danielkesselberg** [comment]
Basically this patch should fix an issue the open suse packager introduced by replacing duplicate files with symlinks right?

**Comment by ggeorgg** [comment]
Exactly.

**Comment by danielkesselberg** [comment]
Build fails because your branch is a bit outdated. Could you merge latest changes from nextclouder/updater?

**Comment by ggeorgg** [comment]
I just merged the latest nextcloud updater repository into my own branch "patch-1". It may look a bit clustered now with my commits. Hope this will not be a problem. I am not quite sure if this is how it works. If it was not correct what I have done, please give me a hint on how to proceed ;)

**Comment by danielkesselberg** [comment]
OK. Sorry there is one more thing. You need to sign off your commits (see this link for more information https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

You have two ways to do this:

A) I would rebase (interactive) the branch to updater/master, squash all commits into one commit, sign these commit off and force push them back.
B) Create a new branch from updater/master, apply your patch again, sign off and open a new pr.

**Pull request closed without merging**
