### PR TITLE
Remove obsolete pipeline php72-master

### PR DESCRIPTION
**Pull request by PVince81**
Master (which is Nextcloud 22) doesn't support PHP 7.2 any more.

For https://github.com/nextcloud/updater/issues/332

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Comment by PVince81** [comment]
I've restarted the build. Hopefully now the devcontainer issue should be gone.

But probably it's too early:
```
% unzip -l latest-master.zip| grep devcont
        0  2021-02-18 00:32   nextcloud/.devcontainer/
      212  2021-02-18 00:32   nextcloud/.devcontainer/setup.sh
     1095  2021-02-18 00:32   nextcloud/.devcontainer/Dockerfile
      346  2021-02-18 00:32   nextcloud/.devcontainer/devcontainer.json
      589  2021-02-18 00:32   nextcloud/.devcontainer/docker-compose.yml
      513  2021-02-18 00:32   nextcloud/.devcontainer/codespace.config.php
```

**Comment by PVince81** [comment]
I've checked the latest master build and the `.devcontainer` is gone.
The build has been restarted, expecting green now.

**Comment by PVince81** [comment]
as the download server is currently overloaded, let's try again later...
`Curl error: Failed to connect to download.nextcloud.com port 443: Connection timed out (Exception)`

**Comment by PVince81** [comment]
restarted again, let's see...

**Comment by PVince81** [comment]
okay, no more timeout, just this:
`Version mismatch - Installed: 22.0.0.1 Wanted: 20.0 (Exception)`

I guess more adjustments are needed since we increased the version on master, I'll take care...

**Comment by PVince81** [comment]
green! it appears that I'm "not authorized to merge this pull request".
can you do it @kesselb ? or someone else ? @nickvergessen @ChristophWurst @juliushaertl

**Pull request merged**
