### PR TITLE
fix appname to just be "Updater"

### PR DESCRIPTION
**Pull request by jancborchardt**
We don’t ever write »Nextcloud« in the header, so no need to do it here.

Please review @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@jancborchardt You forgot to sign your commit:

```
Some commits were not signed off!
Missing signatures on:
- c0992a654243bf9bfc76a07676c929a488ed0523
```

See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work and https://github.com/nextcloud/server/blob/master/contribute/developer-certificate-of-origin

**Comment by jancborchardt** [comment]
@MorrisJobke fixed :)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@MorrisJobke »At least one approved review is required.« ;)

**Comment by MorrisJobke** [comment]
stable9 3e8f358
stable10 b64d12b

**Pull request merged**
