### PR TITLE
Also include *.config.php files

### LINKED ISSUE #384: Updater ignores additional config.php files
As it is described in https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file, it is possible to use multiple config.php files.

Unfortunately, however, the updater.phar file seems to ignore the other config files, which causes the updater to not work properly on some otherwise smoothly running Nextcloud instances.

One problem I and many other Nextcloud users have as a result is the following:
There are hosting plans where the basic file path is different when a user accesses Nextcloud via web browser than when, for example, OCC and updater.phar are accessed via SSH. Then a dynamic adjustment of the datadirectory is necessary.  This can not be done in the config.php, because this could be overwritten by Nextcloud at any time again to a fixed path when updates are applied or the admin changes other values in the settings and hence the main config file gets rebuilt. Therefore, many fix this by creating a separate config file, like this one at https://github.com/froonix/webhosting-mods/blob/master/httpdocs/nextcloud/nextcloud/config/data.config.php to overwrite the value of the config. This works fine except for the updater.

Users of such and other usecases probably wonder why occ works fine, but the updater.phar has problems and may not get the idea that multiple config files are supported for Nextcloud, but not for the updater. If you have read the documentation you don't expect such a behavior and I could imagine that this is responsible for some bug reports.

### PR DESCRIPTION
**Pull request by JensSpanier**
Fixes #384

Inspired by this: https://github.com/nextcloud/server/blob/566586c609253f498c1b3f0c6c004b30ec2d998b/lib/private/Config.php#L205-L252

`index.php` and `updater.phar` still need to be regenerated.

### CODE REVIEW

**Comment by come-nc** [comment]
Please fix DCO by signing off your commit.
Also, use `make index.php updater.phar` to update them.
psalm errors:
```
ERROR: UndefinedVariable - lib/Updater.php:62:10 - Cannot find referenced variable $CONFIG (see https://psalm.dev/024)
			unset($CONFIG);

ERROR: UnresolvableInclude - lib/Updater.php:65:4 - Cannot resolve the given expression to a file path (see https://psalm.dev/106)
			/** @var array $CONFIG */
			require_once $configFile;

ERROR: RedundantConditionGivenDocblockType - lib/Updater.php:67:8 - Docblock-defined type array<array-key, mixed> for $CONFIG is never null (see https://psalm.dev/156)
			if (isset($CONFIG) && is_array($CONFIG)) {

ERROR: RedundantConditionGivenDocblockType - lib/Updater.php:67:8 - Docblock-defined type array<array-key, mixed> for $CONFIG is always array (see https://psalm.dev/156)
			if (isset($CONFIG) && is_array($CONFIG)) {

ERROR: RedundantConditionGivenDocblockType - lib/Updater.php:67:26 - Docblock-defined type array<array-key, mixed> for $CONFIG is always array (see https://psalm.dev/156)
			if (isset($CONFIG) && is_array($CONFIG)) {
```

You should move the `/** @var array $CONFIG */` inside the if I think.
For the unset you may have so use psalm-suppress, or maybe do it at the end of the loop instead of the beginning.

**Comment by JensSpanier** [comment]
Can you please review again? Thanks!

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
@JensSpanier There is a leading space on some lines that codesniffer is complaining about. Please run `composer run cs:fix` to fix it, then `make index.php updater.phar` to update them, and then push the result?

**Comment by JensSpanier** [comment]
> There is a leading space on some lines that codesniffer is complaining about.

Sorry about that. Hope it looks good this time.

**Review by Altahrim — APPROVED** [review]

**Comment by come-nc** [comment]
@JensSpanier This is causing troubles in some cases as explained in https://github.com/nextcloud/server/issues/44157

Is that something that you had the need for yourself? 
I’m not sure what is the best fix, we can catch Throwables from the require I suppose but we cannot log the error I think.
I do not think it’s possible to provide the `OC` class at this point.

**Comment by JensSpanier** [comment]
@come-nc I wasn't aware that the `OC` class can appear in configuration files.
I'm having the same problem like in #384. I'm also hosting at the provider netcup.
I think it would be enough if you could specify the config files that will be read in when calling updater.phar.
Or just another way to overwrite the config parameter `datadirectory` when calling updater.phar.

I also think we should reopen #384 because it's not fixed anymore.

**Pull request merged**
