### PR TITLE
Upgrade Box to latest backwards compatible version (PHP 7.4 compat)

### PR DESCRIPTION
**Pull request by solracsf**
Signed-off-by: Git'Fellow <12234510+solracsf@users.noreply.github.com>

### CODE REVIEW

**Comment by szaimen** [comment]
@solracsf does this fix https://github.com/nextcloud/updater/issues/474?

**Comment by solracsf** [comment]
As per https://github.com/box-project/box/pull/587 yes.

**Comment by szaimen** [comment]
Supserceded by https://github.com/nextcloud/updater/pulls?q=is%3Apr+is%3Aclosed

**Pull request closed without merging**
