### PR TITLE
Run NC master test on > php7.4

### PR DESCRIPTION
**Pull request by tcitworld**

### CODE REVIEW

**Comment by tcitworld** [comment]
Hmm, daily build has extra files in it, where can this be checked or who can check this?

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Hmm, daily build has extra files in it, where can this be checked or who can check this?

We fixed this internally but might need deployment. I forwarded it

**Comment by blizzz** [comment]
could you run `make updater.phar` and commit and push?

**Comment by tcitworld** [comment]
@blizzz that's done in #461

**Pull request merged**
